name: flutter_universal_downloader
description: "A robust Flutter plugin for universal file downloading with Android foreground service support, real-time progress, and cancellation. Ideal for resilient, user-friendly downloads."
version: 0.0.3
homepage: https://github.com/importUsernameDev/flutter_universal_downloader
repository: https://github.com/importUsernameDev/flutter_universal_downloader
issue_tracker: https://github.com/importUsernameDev/flutter_universal_downloader/issues

environment:
  sdk: ^3.7.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_universal_downloader
        pluginClass: FlutterUniversalDownloaderPlugin
